Coursera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'courses.views.view_404'
handler500 = 'courses.views.view_500'
handler403 = 'courses.views.view_403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    path('', include('memberships.urls',namespace='memberships')),
    path('', include('users.urls',namespace='users')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView, create_post, delete_post

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),
    path('blog/create/', create_post, name='create_post'),
    path('blog/<int:id>/delete', delete_post, name='delete_post'),


]

courses/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from courses.views import HomeView,delete_lesson,LessonScheduleView,AboutView,ContactView,CourseListView,edit_row, CourseDetailView,LessonDetailView, SearchView, krijo_klase,delete_row, krijo_lende, krijo_mesim

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('schedule/', LessonScheduleView.as_view(), name='schedule'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('courses/<int:category>', CourseListView, name='course_list'),
    path('courses/<slug>/', login_required(CourseDetailView.as_view()), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', login_required(LessonDetailView.as_view()), name='lesson_detail'),
    path('search/', SearchView, name='kerko_kurs'),
    path('krijo/klase', krijo_klase, name='krijo_klase'),
    path('krijo/lende', krijo_lende, name='krijo_lende'),
    path('krijo/mesim', krijo_mesim, name='krijo_mesim'),
    path('delete/<int:row_id>/', delete_row, name='delete_row'),
    path('edit_row/<int:row_id>/', edit_row, name='edit_row'),
    path('delete_lesson/<str:rday_of_week>/<str:rlesson_number>/', delete_lesson, name='delete_lesson'),
]

memberships/urls.py
from django.urls import path

from memberships.views import MembershipSelectView,PaymentView,UpdateTransactionRecords,CancelSubscription

app_name = 'memberships'

urlpatterns = [
    path('memberships/', MembershipSelectView.as_view(), name='select_membership'),
    path('payments/', PaymentView, name='payment'),
    path('update_transaction/<subscription_id>/update/', UpdateTransactionRecords, name='update_transaction'),
    path('cancel/', CancelSubscription, name='cancel')

]

courses/models.py
from django.db import models
from memberships.models import Membership
from django.contrib.auth.models import User
from django.urls import reverse

class Klasa(models.Model):
    titulli = models.CharField(max_length=150)
    pershkrimi = models.TextField(max_length= 200, null=True)
    imazhi = models.ImageField(upload_to='cat_images', default='cat_images/default.jpg')

    def __str__(self):
        return '{}'.format(self.titulli)

class Lendet(models.Model):
    krijues = models.ForeignKey(User,on_delete = models.CASCADE)
    slug = models.SlugField()
    titulli = models.CharField(max_length=30)
    klasa = models.ForeignKey(Klasa,on_delete=models.CASCADE)
    pershkrimi = models.TextField(max_length=400)
    krijuar_me = models.DateTimeField(auto_now=True)
    imazhi_lendes = models.ImageField(upload_to='kurs_images', default='default.jpg')

    def __str__(self):
        return self.titulli

    def get_absolute_url(self):
        return reverse("courses:course_detail", kwargs={"slug": self.slug})

    def get_courses_related_to_memberships(self):
        return self.courses.all()

    @property
    def lessons(self):
        return self.lesson_set.all().order_by('pozicioni')


class LessonSchedule(models.Model):
    day_of_week = models.CharField(max_length=20)
    lesson_number = models.CharField(max_length=20)
    start_time = models.TimeField()
    end_time = models.TimeField()
    lenda = models.ForeignKey(Lendet,on_delete=models.CASCADE)
    teacher = models.CharField(max_length=50)
    cabinet = models.CharField(max_length=30)
    
    def __str__(self):
        return self.lenda
    
    def get_absolute_url(self):
        return reverse("courses:lesson_detail", kwargs={"course_slug": self.lenda.slug,'lesson_slug':self.slug})


class Lesson(models.Model):
    slug = models.SlugField()
    titulli = models.CharField(max_length=30)
    lenda = models.ForeignKey(Lendet,on_delete=models.CASCADE)
    video_id = models.CharField(max_length=11)
    pozicioni = models.IntegerField()

    def get_upload_path(instance, filename):
        return 'lesson_files/{}/{}'.format(instance.lenda.slug, filename)

    files = models.FileField(upload_to=get_upload_path)

    def __str__(self):
        return self.titulli

    def get_absolute_url(self):
        return reverse("courses:lesson_detail", kwargs={"course_slug": self.lenda.slug,'lesson_slug':self.slug})

courses/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Klasa, Lendet, Lesson, LessonSchedule

class KlasaForm(forms.ModelForm):
    class Meta:
        model = Klasa
        fields = '__all__'
        help_texts = {
            'titulli': 'Например, 11 класс или Класс информатики',
            'pershkrimi': 'Введите краткое описание класса',
            'imazhi': 'Можно загрузить фотографию класса или оставить поле пустым',
        }
        labels = {
            'titulli': 'Название класса',
            'pershkrimi': 'Описание',
            'imazhi': 'Загрузить фото',
        }

class LendaForm(forms.ModelForm):
    class Meta:
        model = Lendet
        fields = ['krijues','slug', 'titulli', 'klasa', 'pershkrimi', 'imazhi_lendes']
        help_texts = {
            'titulli': 'Например, Математика, География и т.д.',
            'pershkrimi': 'Введите краткое описание предмета',
            'klasa': 'Выберите класс, для которого создается предмет',
            'imazhi_lendes': 'Можно загрузить фотографию предмета или оставить поле пустым',
        }
        labels = {
            'titulli': 'Название предмета',
            'klasa': 'Класс',
            'pershkrimi': 'Описание',
            'imazhi_lendes': 'Загрузить фото',
        }
        
        widgets = {'krijues': forms.HiddenInput(), 'slug': forms.HiddenInput()}


class MesimiForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['slug','titulli', 'lenda', 'video_id', 'pozicioni', 'files', ]
        help_texts = {
            'titulli':'Введите название урока',
            'lenda':'Выберите предмет, к которому относится данный урок',
            'video_id':'Введите идентификатор видео на YouTube, которое вы хотите загрузить (<a href="/media/youtube_help.png">где найти идентификатор</a>)',
            'pozicioni':'Укажите номер позиции или порядковый номер урока в рамках предмета',
            'files' : 'Файлы для обучения',
        }
        labels = {
            'titulli': 'Название урока',
            'lenda': 'Название предмета',
            'video_id': 'Видео id',
            'pozicioni': 'Номер урока',
            'files': 'Файл',



        }
        widgets = {
            'slug': forms.HiddenInput()
        }
            
class LessonScheduleForm(forms.ModelForm):
    class Meta:
        model = LessonSchedule
        fields = ['day_of_week', 'lesson_number','start_time','end_time', 'lenda', 'teacher', 'cabinet']
        help_texts = {
            'day_of_week':'Введите название урока',
            'lesson_number':'Выберите предмет, к которому относится данный урок',
            'start_time':'Введите время начала урока',
            'end_time':'Введите ремя конца урока',
            'lenda':'Выберите название предмета',
            'teacher':'Укажите номер позиции или порядковый номер урока в рамках предмета',
            'cabinet':'Укажите номер позиции или порядковый номер урока в рамках предмета',
        }

courses/views.py
import secrets
from django.shortcuts import render, redirect
from django.views.generic import TemplateView,ListView,DetailView,View
from courses.models import Lendet,Lesson,Klasa, LessonSchedule
from memberships.models import UserMembership
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import KlasaForm, LendaForm, MesimiForm,LessonScheduleForm
from django.urls import reverse_lazy
from django.views.generic import UpdateView
# Create your views here.

class HomeView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Klasa.objects.all()
        context['category'] = category
        return context

class AboutView(TemplateView):
    template_name = 'about.html'


class ContactView(TemplateView):
    template_name = 'contact.html'
# lesson = get_object_or_404(Lesson, pozicioni=row_id)
    
#     if not request.user.profile.is_teacher:
#         messages.error(request, f'Ваша учетная запись не имеет доступа к этому URL-адресу, только учетные записи учителей!')
#         return redirect('courses:home')
    
#     if request.method == 'POST':
#         form = MesimiForm(request.POST, request.FILES, instance=lesson)
#         if form.is_valid():
#             form.save()
#             messages.success(request, f'Ваш класс был изменен.')
#             return redirect('/courses/1')
#     else:
#         form = MesimiForm(instance=lesson)

#     context = {'form': form}
#     return render(request, 'courses/krijo_mesim.html', context)
class LessonScheduleView(ListView):

    def get(self, request):
        
        schedule = LessonSchedule.objects.all()
        form = LessonScheduleForm()
        context = {'schedule': schedule, 'form':form}
        return render(request, 'courses/schedule.html', context)

    def post(self, request):
        form = LessonScheduleForm(request.POST)
        form.save()

        return redirect('/schedule/')
    
def CourseListView(request, category):
    courses = Lendet.objects.filter(klasa=category)
    context = {
        'courses':courses
    }
    return render(request, 'courses/course_list.html', context)


@login_required
def delete_lesson(request,rday_of_week,rlesson_number):
    if not request.user.profile.is_teacher == True:
        messages.error(request, f'Ваша учетная запись не имеет доступа к этому URL-адресу, только учетные записи учителей!')
        return redirect('courses:home')
    try:
        form = LessonSchedule.objects.get(day_of_week=rday_of_week,lesson_number=rlesson_number)
        form.delete()
        return redirect('/schedule/')
    except Exception:
        return render(request, 'error.html')
    
class CourseDetailView(DetailView):
    context_object_name = 'course'
    template_name = 'courses/course_detail.html'
    model = Lendet
    
@login_required
def edit_lesson(request,rday_of_week,rlesson_number):
    # Получаем объект из БД по переданному id.
    lesson = get_object_or_404(LessonSchedule, day_of_week=rday_of_week,lesson_number=rlesson_number)
    
    if not request.user.profile.is_teacher:
        messages.error(request, f'Ваша учетная запись не имеет доступа к этому URL-адресу, только учетные записи учителей!')
        return redirect('courses:home')
    
    if request.method == 'POST':
        form = LessonSchedule(request.POST, instance=lesson)
        if form.is_valid():
            form.save()
            messages.success(request, f'Ваше расписание было изменено.')
            return redirect('/courses/1')
    else:
        form = LessonSchedule(instance=lesson)

    context = {'form': form}
    return render(request, 'courses/krijo_mesim.html', context)
    
class CourseDetailView(DetailView):
    context_object_name = 'course'
    template_name = 'courses/course_detail.html'
    model = Lendet


 
class LessonDetailView(View,LoginRequiredMixin):
    def get(self, request, course_slug, lesson_slug, *args, **kwargs):
        course = get_object_or_404(Lendet, slug=course_slug)
        lesson = get_object_or_404(Lesson, slug=lesson_slug)
        context = {'lesson': lesson}
        return render(request, "courses/lesson_detail.html", context)


@login_required
def SearchView(request):
    if request.method == 'POST':
        kerko = request.POST.get('search')
        results = Lesson.objects.filter(titulli__contains=kerko)
        context = {
            'results':results
        }
        return render(request, 'courses/search_result.html', context)
@login_required
def delete_row(request,row_id):
    if not request.user.profile.is_teacher == True:
        messages.error(request, f'Ваша учетная запись не имеет доступа к этому URL-адресу, только учетные записи учителей!')
        return redirect('courses:home')
    try:
        form = Lesson.objects.get(pozicioni=row_id)
        form.delete()
        return redirect('/courses/1')
    except Exception:
        return render(request, 'error.html', {'message': f"Строка с ID {row_id} не найдена"})

@login_required
def krijo_klase(request):
    if not request.user.profile.is_teacher == True:
        messages.error(request, f'Ваша учетная запись не имеет доступа к этому URL-адресу, только учетные записи учителей!')
        return redirect('courses:home')
    if request.method == 'POST':
        form = KlasaForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f'Ваш класс был создан.')
            return redirect('courses:home')
    else:
        form = KlasaForm()
    context = {
        'form':form
    }
    return render(request, 'courses/krijo_klase.html', context)


@login_required
def krijo_lende(request):
    if not request.user.profile.is_teacher == True:
        messages.error(request, f'Ваша учетная запись не имеет доступа к этому URL-адресу, только учетные записи учителей!')
        return redirect('courses:home')
    if request.method == 'POST':
        form = LendaForm(request.POST)
        if form.is_valid():
            form.save()
            klasa = form.cleaned_data['klasa']
            slug = klasa.id
            messages.success(request, f'Ваш класс был создан.')
            return redirect('/courses/' + str(slug))
    else:
        form = LendaForm(initial={'krijues':request.user.id, 'slug':secrets.token_hex(nbytes=16)})
    context = {
        'form':form
    }
    return render(request, 'courses/krijo_lende.html', context)


@login_required
def krijo_mesim(request):
    if not request.user.profile.is_teacher == True:
        messages.error(request, f'Ваша учетная запись не имеет доступа к этому URL-адресу, только учетные записи учителей!')
        return redirect('courses:home')
    if request.method == 'POST':
        form = MesimiForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            lenda = form.cleaned_data['lenda']
            slug = lenda.slug
            messages.success(request, f'Ваш класс был создан.')
            return redirect('/courses/' + str(slug) )
    else:
        form = MesimiForm(initial={'slug':secrets.token_hex(nbytes=16)})
    context = {
        'form':form
    }
    return render(request, 'courses/krijo_mesim.html', context)

@login_required
def edit_row(request, row_id):
    # Получаем объект из БД по переданному id.
    lesson = get_object_or_404(Lesson, pozicioni=row_id)
    
    if not request.user.profile.is_teacher:
        messages.error(request, f'Ваша учетная запись не имеет доступа к этому URL-адресу, только учетные записи учителей!')
        return redirect('courses:home')
    
    if request.method == 'POST':
        form = MesimiForm(request.POST, request.FILES, instance=lesson)
        if form.is_valid():
            form.save()
            messages.success(request, f'Ваш класс был изменен.')
            return redirect('/courses/1')
    else:
        form = MesimiForm(instance=lesson)

    context = {'form': form}
    return render(request, 'courses/krijo_mesim.html', context)




def view_404(request, exception):
    return render(request, '404.html')

def view_403(request, exception):
    return render(request, '403.html')

def view_500(request):
    return render(request, '500.html')

# def get(self,request,course_slug,lesson_slug,*args,**kwargs):
#
#     course_qs = Course.objects.filter(slug=course_slug)
#     if course_qs.exists():
#         course = course_qs.first()
#     lesson_qs = course.lessons.filter(slug=lesson_slug)
#     if lesson_qs.exists():
#         lesson = lesson_qs.first()
#     user_membership = UserMembership.objects.filter(user=request.user).first()
#     user_membership_type = user_membership.membership.membership_type
#
#     course_allowed_membership_type = course.allowed_memberships.all()
#     context = {'lessons':None}
#
#     if course_allowed_membership_type.filter(membership_type=user_membership_type).exists():
#         context = {'lesson':lesson}
#
#     return render(request,'courses/lesson_detail.html',context)

courses/templates/courses/course_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Информация о странице -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/2.jpg' %}">
<div class="container">
<div class="site-breadcrumb">
<a href="/">Главная</a>
<span>Класс /</span>
<span>Уроки</span>
</div>
</div>
</div>
<!-- Конец информации о странице -->

<!-- Раздел поиска -->
<section class="search-section ss-other-page">
<div class="container">
<div class="search-warp">
<div class="section-title text-white">
<h2><span>Искать курсы</span></h2>
</div>
<div class="row">
<div class="col-lg-10 offset-lg-1">
<!-- Форма поиска -->
<form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter"> {% csrf_token %}
<input name="search" type="text" placeholder="Найти курс">
<button type="submit" class="site-btn btn-dark">Найти курс</button>
</form>
</div>
</div>
</div>
</div>
</section>
<!-- Конец раздела поиска -->

<!-- Раздел одного курса -->
<section class="single-course spad pb-0">
<div class="container">
<div class="course-meta-area">
<div class="row">
<div class="col-lg-10 offset-lg-1">
  <h3>{{course.titulli|capfirst}}</h3>
      <div class="course-metas">
        <div class="course-meta">
          <div class="course-author">
            <h6>Учитель</h6>
            <p>{{course.krijues|capfirst}}, <span>Учитель</span></p>
          </div>
        </div>
        <div class="course-meta">
          <div class="cm-info">
            <h6>Класс</h6>
            <p>{{course.klasa}}</p>
          </div>
        </div>
        <div class="course-meta">
          <div class="cm-info">
            <h6>Описание класса</h6>
            <p>{{course.pershkrimi}}</p>
          </div>
        </div>
        <div class="course-meta">
          <div class="cm-info">
            <h6>Количество уроков</h6>
            <p>{{ course.lessons|length }}</p>
          </div>
        </div>
      </div>
      <a href="/courses/{{ course.id }}" class="site-btn price-btn">Назад</a>
      <a href="#vazhdo" class="site-btn buy-btn">Продолжить урок</a>
    </div>
  </div>
</div>
<img src="img/courses/single.jpg" alt="" class="course-preview">
<div class="row">
  <div class="col-lg-10 offset-lg-1 course-list">
    <div class="cl-item" id="lessons">
      <h4>Уроки в этом классе</h4>
      {% if course.lessons != None  %}
        {% for lesson in course.lessons %}
        <div data-aos="fade-right" >
          <h5 class="pb-3">Урок {{lesson.pozicioni}} <a id="vazhdo" href="{{ lesson.get_absolute_url }}#video"><span class="pl-4">{{lesson.titulli}}</span></a></h5>
          {% if request.user.profile.is_teacher == True %}
          <a href="{% url 'courses:edit_row' lesson.pozicioni %}" class="change-btn">Редактировать урок</a>
          <a href="{% url 'courses:delete_row' lesson.pozicioni %}" class="delete-btn">Удалить урок</a>
          {% endif %} 
        </div>
        {% endfor %}
      {% endif %}
      {% if course.lessons|length == 0 %}
      <div class="alert alert-danger">Пока нет уроков для этого класса!</div>
      {% endif %} 
    </div>
  </div>
</div>
</div>
</section>

{% endblock %}

courses/templates/courses/course_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/1.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Kryefaqja</a>
      <span>Курсы</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- search section -->
<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Поиск курсов</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter"> {% csrf_token %}
            <input name="search" type="text" placeholder="Поиск курсов">
            <button type="submit" class="site-btn btn-dark">Поиск курсов</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->

<div class="course-warp">
  <ul class="course-filter controls">
    <li class="control active" data-filter="all">Все части этого класса</li>
  </ul>
<div class="featured-courses">

      <div class="featured-course course-item">
        <div class="row">
          {% for course in courses %}
          <div class="col-lg-6 pb-4">
            <div class="course-info">
              <div class="course-text">
                <h5>{{course.klasa}}</h5>
                <a href="{% url 'courses:course_detail' course.slug %}"><h3 class="">{{course.titulli|capfirst}}</h3></a>
                <p>{{course.pershkrimi}}</p>
                <div class="students"><a href="{% url 'courses:course_detail' course.slug %}" class="btn btn-primary">Занятия</a></div>
              </div>
              <div class="course-author">
                <div class="ca-pic set-bg" data-setbg="{{ request.user.profile.profile_pic.url }}"></div>
                <p>Создан: {{course.krijues|capfirst}}, <span>Учитель </span></p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

courses/templates/courses/edit_row.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>Редактировать урок</h1>
        <form method="post" enctype='multipart/form-data' novalidate>{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn mb-4 btn-primary">Сохранить изменения</button>
        </form>
</div>
{% endblock %}

courses/templates/courses/krijo_klase.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<h1>Создать класс</h1>
<form method="post" action="/krijo/klase" enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<button type="submit" class="btn mb-4 btn-primary">Создать класс</button>
</form>
</div>
{% endblock %}

courses/templates/courses/krijo_lende.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>Создать материалы</h1>
        <form method="post" action="/krijo/lende" enctype='multipart/form-data'>{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn mb-4 btn-primary">Создать материалы</button>
        </form>
</div>
{% endblock %}

courses/templates/courses/krijo_mesim.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>Создать урок</h1>
        <form method="post" enctype='multipart/form-data' novalidate>{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn mb-4 btn-primary">Создать урок</button>
        </form>
</div>
{% endblock %}

courses/templates/courses/lesson_detail.html
{% extends 'base.html' %}
{% load static %}
{% block post_detail_link %}

{% endblock %}

{% block content %}
<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/2.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Kryefaqja</a>
      <span>Класс /</span>
      <span>Обучение /</span>
      <span>Видео </span>
    </div>
  </div>
</div>
  <!-- {% if lesson is not None %}
	<li class="form-control"><a  href="{{ lesson.course.get_absolute_url }}">Mesimi : {{ lesson.course.titulli }}</a></li>
	<li class="form-control">Title : {{ lesson.titulli }}</li>
  {% endif %} -->

<!-- Page info end -->

	<div  id="video" class='container'>
		<div class="alert alert-info" role="alert">
			Нажмите 2 раза для видео на весь экран!
		  </div>
		<h1>{{ lesson.titulli }}</h1>
		<div class='row'>
			<div class='col-sm-12 col-md-12'>
				{% if lesson is not None %}

				<iframe id="video" width="100%" height="450px" src="https://www.youtube-nocookie.com/embed/{{ lesson.video_id }}?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

				<div class="text-center">
				<a href="javascript:history.back()" class="mb-5 mt-2 btn btn-primary">Вернуться к обучению</a>
				</div>
				<div class="text-center">
				<a href="/media/{{lesson.files}}" class="mb-5 mt-2 btn btn-primary" download>Скачать приклеплённый к занятию файл</a>
				</div>
				{% else %}
				<!-- <h3>Upgrade membership</h3>
				<p>To view this course you'll need to upgrade your membership</p>
				<br>
				<a href="{% url 'memberships:select_membership' %}"><button class="btn btn-warning">Upgrade Membership</button></a>
				<hr> -->
				{% endif %}
			</div>
		</div>
	</div>

{% endblock content %}

courses/templates/courses/schedule.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1>Расписание</h1>
  <table>
    <thead>
      <tr>
        <th>День недели</th>
        <th>Время начала</th>
        <th>Время конца</th>
        <th>Номер занятия</th>
        <th>Предмет</th>
        <th>Учитель</th>
        <th>Кабинет</th>
      </tr>
    </thead>
    <tbody>
      {% for lesson in schedule %}
        <tr>
          <td>{{ lesson.day_of_week }}</td>
          <td>{{ lesson.start_time|time:"H:i" }}</td>
          <td>{{ lesson.end_time|time:"H:i" }}</td>
          <td>{{ lesson.lesson_number }}</td>
          <td>{{ lesson.lenda }}</td>
          <td>{{ lesson.teacher }}</td>
          <td>{{ lesson.cabinet }}</td>
          {% if request.user.profile.is_teacher == True %}
          
          <td><a href="{% url 'courses:delete_lesson'  lesson.day_of_week lesson.lesson_number %}">Удалить урок</a></td>
          {% endif %} 
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">Пока ещё нет занятий</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% if request.user.profile.is_teacher == True %}
          
  <hr>
  <h2>Добавить занятие</h2>
  <form method="post" enctype='multipart/form-data' novalidate>{% csrf_token %}
    {{form.as_p }}
    <button type="submit" class="btn mb-4 btn-primary">Сохранить изменения</button>
  </form>
  
  {% comment %} <form method="post">
    
    <label for="day_of_week">День недели:</label>
    <input type="text" name="day_of_week" required><br>
    <label for="start_time">Начало занятия:</label>
    <input type="time" name="start_time" required><br>
    <label for="end_time">Конец занятия:</label>
    <input type="time" name="end_time" required><br>
    <label for="lesson_number">Номер урока:</label>
    <input type="text" name="lesson_number" required><br>
    <label for="subject">Предмет:</label>
    <input type="text" name="subject" required><br>
    <label for="teacher">Учитель:</label>
    <input type="text" name="teacher" required><br>
    <label for="cabinet">Кабинет:</label>
    <input type="text" name="cabinet" required><br>
    <button type="submit">Добавить Урок</button>
    
  </form> {% endcomment %}
  {% endif %} 
{% endblock %}