Coursera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'courses.views.view_404'
handler500 = 'courses.views.view_500'
handler403 = 'courses.views.view_403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    path('', include('memberships.urls',namespace='memberships')),
    path('', include('users.urls',namespace='users')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView, create_post, delete_post

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),
    path('blog/create/', create_post, name='create_post'),
    path('blog/<int:id>/delete', delete_post, name='delete_post'),


]

courses/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from courses.views import HomeView,delete_lesson,LessonScheduleView,AboutView,ContactView,CourseListView,edit_row, CourseDetailView,LessonDetailView, SearchView, krijo_klase,delete_row, krijo_lende, krijo_mesim

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('schedule/', LessonScheduleView.as_view(), name='schedule'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('courses/<int:category>', CourseListView, name='course_list'),
    path('courses/<slug>/', login_required(CourseDetailView.as_view()), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', login_required(LessonDetailView.as_view()), name='lesson_detail'),
    path('search/', SearchView, name='kerko_kurs'),
    path('krijo/klase', krijo_klase, name='krijo_klase'),
    path('krijo/lende', krijo_lende, name='krijo_lende'),
    path('krijo/mesim', krijo_mesim, name='krijo_mesim'),
    path('delete/<int:row_id>/', delete_row, name='delete_row'),
    path('edit_row/<int:row_id>/', edit_row, name='edit_row'),
    path('delete_lesson/<str:rday_of_week>/<str:rlesson_number>/', delete_lesson, name='delete_lesson'),
]

users/urls.py
from django.urls import path

from users.views import Profile, kerkesa

app_name = 'users'

urlpatterns = [
    path('profile/', Profile, name='profile'),
    path('kerkesa/', kerkesa, name='kerkesa')

]

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Главная</a>
      <span>О нас</span>
	</div>
</div>
</div>
<!-- Page info end -->


<section class="about-us py-5 " id="about-us">
  <div class="container mt-5">
  <div class="row">
	  <div class="col-md-6">
		  <h1 class='text-primary'>Добро пожаловать!</h1>
		  <h2>Узнайте больше о нас</h2>
		  <hr>
		  <p>ZXCschool – ресурс, помогающий студентам успешно подготовиться к экзаменам и не только!</p>
		  <p>Наша цель – обеспечить удобную и качественную подготовку студентов к сессии и не только! На портале вы найдете полезные материалы для самостоятельного изучения.</p>
		  <button type="button" class="btn btn-primary">Давайте узнаем больше</button>

	  </div>
	  <div class="col-md-6">
		  <img src="http://themebubble.com/demo/marketingpro/wp-content/uploads/2016/10/seo-slide.png "alt="">
	  </div>
  </div>
</div>
</section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>ZXCSchool</title>
	<meta charset="UTF-8">
	<meta name="description" content="WebUni Education Template">
	<meta name="keywords" content="webuni, education, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="{% static 'webuni/img/favicon.png' %}" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'webuni/css/bootstrap.min.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/style.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/freelancer.css'%}"/>
	<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />


	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<nav class="navbar navbar-expand-lg bg-secondary text-uppercase" id="mainNav">
		<div class="container">
		  <a class="navbar-brand js-scroll-trigger" href="/"><img src="{% static 'webuni/img/logo2.png' %}" alt=""></a>
		  <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			Меню

		  </button>
		  <div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:home' %}">Домой</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<li class="nav-item mx-0 mx-lg-1">
					<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/#kurset">Курсы</a>
				  </li>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:schedule' %}">Расписание</a>
			  </li>
			  {% if request.user.profile.is_teacher == True %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:krijo_klase' %}">Создать класс</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:krijo_lende' %}">Создавайте материалы</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:krijo_mesim' %}">Создать урок</a>
			  </li>
			  {% else %}
			  
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:contact' %}">Контакт</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:about' %}">О нас</a>
			  </li>
			  {% endif %}
			  {% if request.user.is_authenticated %}

			  <div class="dropdown show">
				<a class=" dropdown-toggle nav-link py-3 px-0 px-lg-3 rounded js-scroll-triggeraa" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					{{request.user.username}}
				</a>

				<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
				  <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
				  <a class="dropdown-item" href="{% url 'account_logout' %}">Выход</a>
				</div>
			  </div>
			  {% else %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="active nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'account_login' %}">Авторизоваться</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="active nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'account_signup' %}">Зарегистрировать</a>
			  </li>
              {% endif %}
			</ul>
		  </div>
		</div>
	  </nav>
	  <script>
		let prevScrollpos = window.pageYOffset;
		let scrollThresholdPercent = 0.2; // 20%
	
		window.onscroll = function() {
			let currentScrollPos = window.pageYOffset;
			let screenHeight = window.innerHeight;
			let scrollThresholdPixels = screenHeight * scrollThresholdPercent;
	
			if (prevScrollpos > currentScrollPos && currentScrollPos > scrollThresholdPixels) {
				document.getElementById("mainNav").style.position = "fixed";
			} else {
				document.getElementById("mainNav").style.position = "relative";
			}
			prevScrollpos = currentScrollPos;
		}
	</script>

{% include 'inc/messages.html' %}
{% block content %}

{% endblock content %}

{% if request.user.is_authenticated %}
{% else %}
	<!-- banner section -->
	<section class="banner-section spad">
		<div class="container">
			<div class="section-title mb-0 pb-2">
				<h2>Присоединяйтесь к нашему сообществу!</h2>
				<p>Изучайте бесплатные онлайн-уроки и школьные занятия с помощью видеороликов и общения с учителями и другими участниками MesoOn. Это очень просто, единственное, что вам нужно сделать, это зарегистрироваться. Нажмите ниже: </p>
			</div>
			<div class="text-center pt-5">
				<a href="{% url 'account_signup' %}" class="site-btn">Зарегистрируйтесь сейчас</a>
			</div>
		</div>
	</section>
	<!-- banner section end -->
{% endif %}


	<!-- footer section -->
	<footer class="footer-section spad pb-0">
		<div class="footer-top">
			<div class="footer-warp">
					<div class="widget-item">
						<h4>Контактная информация</h4>
						<ul class="contact-list">
							<li>Албания <br>Мамурра</li>
							<li>+89053484771</li>
							<li>Antoncsgo@rambler.ru</li>
						</ul>
					</div>
			</div>
		</div>
	</footer>
	<!-- footer section end -->


	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'webuni/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'webuni/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'webuni/js/mixitup.min.js' %}"></script>
	<script src="{% static 'webuni/js/circle-progress.min.js' %}"></script>
	<script src="{% static 'webuni/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'webuni/js/main.js' %}"></script>
	<script src="{% static 'webuni/js/freelancer.js' %}"></script>
	<script src="{% static 'webuni/js/youtube.js' %}"></script>
	<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Главная</a>
      <span>Контакты</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- search section -->
<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Найдите свой курс</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form class="course-search-form">
            <input type="text" placeholder="Курс">
            <input type="text" class="last-m" placeholder="Категория">
            <button class="site-btn btn-dark">Искать курс</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->



<!-- Page -->
<section class="contact-page spad pb-0">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="contact-form-warp">
          <div class="section-title text-white text-left">
            <h2>Связаться с нами</h2>
            <p>Напишите ваше обращение к нам, нам оно очень не важно.</p>
          </div>
          <form class="contact-form">
            <input type="text" placeholder="Ваше Имя">
            <input type="text" placeholder="Ваш E-mail">
            <input type="text" placeholder="Предмет">
            <textarea placeholder="Сообщение"></textarea>
            <button class="site-btn">Отправленное сообщение</button>
          </form>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="contact-info-area">
          <div class="section-title text-left p-0">
            <h2>Контактная информация</h2>
          </div>
          <div class="phone-number">
            <span>Прямая линия</span>
            <h2>88005553535</h2>
          </div>
          <ul class="contact-list">
            <li>Молочный переулок, 4 <br>Ульяновск, Россия</li>
            <li>+89378838255</li>
            <li>zxCursed@rambler.ru</li>
          </ul>
          <div class="social-links">
            <a href="#"><i class="fa fa-pinterest"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-behance"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Hero section -->
<section class="hero-section set-bg" data-setbg="{% static 'webuni/img/bg.jpg'%}">
  <div class="container">
    <div class="hero-text text-white">
      {% if request.user.is_authenticated %}
      <h2>Добро Пожаловать{% if request.user.profile.is_teacher == True %}
        учитель,
        {% endif %} {{ request.user.username|capfirst }}


      </h2>
      {% else %}
      <h2>Лучшие бесплатные онлайн-курсы</h2>
      {% endif %}
      <p>ZXCSchool - это онлайн-платформа для проведения школьных лекций преданным своему делу персоналом с опытными преподавателями и тренерами, которые облегчат процесс обучения простым способом с помощью видеороликов.</p>
    </div>
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter"> {% csrf_token %}
          <input name="search" type="text" placeholder="Искать курсы">
          <button type="submit" class="site-btn">Искать курсы</button>
        </form>
      </div>
    </div>
  </div>
</section>
<!-- Hero section end -->

<!-- categories section -->
<section class="categories-section spad">
  <div class="container">
    <div class="section-title">
      <h2 id="kurset">Категории и классы</h2>
      <p>Классы делятся на различные категории в зависимости от предмета и преподавателя. Вы должны сначала зарегистрироваться, а затем посещать занятия.</p>
    </div>
    <div class="row">
      {% for cat in category %}
      <!-- categorie -->
      <div data-aos="zoom-in" class="col-lg-4 col-md-6">
        <div class="categorie-item">
          <div class="ci-thumb set-bg" data-setbg="{{ cat.imazhi.url }}"></div>
          <div class="ci-text">

            <h5>{{cat.titulli|capfirst}}</h5>

            <p>{{ cat.pershkrimi|capfirst }}</p>
            <span><a class="btn btn-success" href="/courses/{{ cat.id }}">Просмотреть</a></span>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- categories section end -->
{% if request.user.is_authenticated %}
{% else %}
<section class="course-section spad">
  <div class="container">
    <div class="section-title mb-0">
      <h2>Примеры курсов</h2>
      <p class="pb-3">Вот несколько примеров курсов, которые студенты посещают на нашей платформе.</p>
    </div>
  </div>
  <div class="course-warp">
    <div class="row course-items-area">
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 finance">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <div class="youtube" id="6K83dgjkQNw" style="width: 100%; height: 290px;"></div>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>Геометрия</h5>
              <p>Математика 10</p>
              <div class="students">Класс 10</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/balda.jfif' %}"></div>
              <p>Никита Ивановна, <span>Учителя</span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 design">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <div class="youtube" id="6K83dgjkQNw" style="width: 100%; height: 290px;"></div>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>Электролиз</h5>
              <p>Химия</p>
              <div class="students">Класс 11</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/ramisb.png' %}"></div>
              <p>Рамись Зайнулович, <span>Учителя</span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 web">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <div class="youtube" id="6K83dgjkQNw" style="width: 100%; height: 290px;"></div>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>Тригонометрия</h5>
              <p>Математика</p>
              <div class="students">Класс 10</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/ramisb.png' %}"></div>
              <p>Рамись Зайнулович, <span>Учителя</span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 photo">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <div class="youtube" id="6K83dgjkQNw" style="width: 100%; height: 290px;"></div>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>Электрическая цепь</h5>
              <p>Физика</p>
              <div class="students">Класс 10</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/ramisb.png' %}"></div>
              <p>Рамись Зайнулович, <span>Учителя</span></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endif %}
<!-- course section end -->

{% if request.user.is_authenticated %}

<!-- signup section -->
{% if request.user.profile.is_teacher == True %}
<div class="container">
  <h1 class="text-center">Ваша учетная запись имеет доступ к учителю</h1><br>
  <p class="text-center">Имея учетную запись преподавателя, вы уже имеете полный доступ к этой платформе. Вы можете выполнять больше функций, чем в первоначальной учетной записи студента. Некоторыми из этих функций являются:</p>

  <div data-aos="fade-right" class="row mt-4 mb-4 bg-light">
    <div class="col-md-4 text-center">
      <h3 class="p-4">Вы можете создать свой собственный класс</h3>
      <a href="{% url 'courses:krijo_klase' %}" class="btn btn-outline-primary m-4">Создать класс</a>
    </div>
    <div class="col-md-8">
      <img class="img-fluid w-100" src="{% static 'webuni/img/categories/4.jpg' %}" alt="">
    </div>
  </div>

  <div data-aos="fade-left" class="row mt-4 mb-4 bg-light">
      <div class="col-md-8">
        <img class="img-fluid w-100" src="{% static 'webuni/img/categories/2.jpg' %}" alt="">
      </div>

    <div class="col-md-4 text-center">
      <h3 class="p-4">Вы можете создать свой собственный курс</h3>
      <a href="{% url 'courses:krijo_lende' %}" class="btn btn-outline-primary m-4">Создать цепочку</a>
  </div>
</div>

<div data-aos="fade-right" class="row mt-4 mb-4 bg-light">
  <div class="col-md-4 text-center">
    <h3 class="p-4">Вы можете загружать свои собственные уроки и видео.</h3>
    <a href="{% url 'courses:krijo_mesim' %}" class="btn btn-outline-primary m-4">Создайте урок</a>
  </div>
  <div class="col-md-8">
    <img class="img-fluid w-100" src="{% static 'webuni/img/categories/1.jpg' %}" alt="">
  </div>
</div>
</div>

{% else %}
<section data-aos="zoom-out" class="signup-section spad">
  <div class="signup-bg set-bg" data-setbg="{% static 'webuni/img/signup-bg.jpg' %}"></div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6">
        <div class="signup-warp">
          <div class="section-title text-white text-left">
            <h2>Зарегистрируйтесь в качестве учителей</h2>
            <p>Чтобы зарегистрироваться в качестве преподавателя на платформе, вы должны заполнить поля ниже, и тогда у вас будет полный доступ к загрузке курсов и видеороликов.</p>

          </div>
          <!-- signup form -->
          <form action="/kerkesa/" method="post" class="signup-form">{% csrf_token %}
            <input type="text" placeholder="Имя" name="name">
            <input type="text" placeholder="Email" name="e-mail">
            <input type="text" placeholder="Номер телефона" name="phone">
            <button class="site-btn">Отправить запрос</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endif %}
<!-- signup section end -->
{% else %}
{% endif %}

{% endblock content %}